[package]
name = "dailies"
version = "0.2.3-a.1"
edition = "2024"
rust-version = "1.90.0"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }
vergen-gitcl = { version = "9.0.1", features = ["build", "cargo", "rustc"] }

[dependencies]
anyhow = "1.0.100"
argon2 = { version = "0.5.3", features = ["std"] }
chrono = { version = "0.4.42", features = ["serde"] }
futures = "0.3.31"
futures-util = "0.3.31"
lazy_static = "1.5.0"
libsqlite3-sys = { version = "0.30.1", features = ["bundled"] }
log = "0.4"
rand = "0.10.1"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
serde_with = "3.14.1"
sqlite-hashes = { version = "0.10.7", default-features = false, features = ["hex", "sha1"] }
sqlx = { version = "0.8.6", features = ["derive", "chrono", "macros", "runtime-tokio", "sqlite", "migrate"] }
strum = { version = "0.27.2", features = ["derive"] }
tauri = { version = "2.8.5", features = ["protocol-asset", "config-toml"] }
tauri-plugin-android-fs = "24.0.0"
tauri-plugin-fs = "2.4.2"
tauri-plugin-http = "2"
tauri-plugin-log = "2"
tauri-plugin-os = "2"
tauri-plugin-process = "2"
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["full"] }

[dev-dependencies]
tauri-plugin-devtools = "2.0.0"

[profile.dev.package.sqlx-macros]
opt-level = 3
