CREATE TABLE IF NOT EXISTS "sessions" (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user TEXT NOT NULL,
  session_id TEXT NOT NULL,
  FOREIGN KEY (user) REFERENCES "users" (name) ON DELETE CASCADE ON UPDATE CASCADE
);
