[language-server.rust-analyzer]
command = "rust-analyzer"

  [language-server.rust-analyzer.config]
  cargo.features                                 = "all"
  cargo.targetDir                                = true
  check.command                                  = "check"
  inlayHints.bindingModeHints.enable             = false
  inlayHints.closingBraceHints.minLines          = 10
  inlayHints.closureReturnTypeHints.enable       = "with_block"
  inlayHints.discriminantHints.enable            = "fieldless"
  inlayHints.lifetimeElisionHints.enable         = "skip_trivial"
  inlayHints.typeHints.hideClosureInitialization = false
  lruCapacity                                    = 16384
  lru.capacity                                   = 16384
  diagnostics.disabled                           = ["unlinked-file"]

    [language-server.rust-analyzer.config.files]
    watcher = "server"
    # watcher = "default"

[[language]]
name                          = "rust"
shebangs                      = ["rust-script", "cargo"]
auto-format                   = true
language-servers              = ["rust-analyzer", "tailwindcss-ls"]
indent                        = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]

  [language.formatter]
  command = "rustfmt"
  args    = ["+nightly"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args    = ["--stdio"]

  [language-server.tailwindcss-ls.config]
  userLanguages = { rust = "html", "*.rs" = "html" }

[language-server.typescript-language-server]
command = "typescript-language-server"
args    = ["--stdio"]

  [language-server.typescript-language-server.config]
  hostInfo = "helix"

[language-server.vscode-eslint-language-server]
command = "vscode-eslint-language-server"
args    = ["--stdio"]

  [language-server.vscode-eslint-language-server.config]
  validate            = "on"
  experimental        = { useFlatConfig = false }
  rulesCustomizations = []
  run                 = "onType"
  problems            = { shortenToSingleLine = false }
  nodePath            = ""

    [language-server.vscode-eslint-language-server.config.codeAction.disableRuleComment]
    enable   = true
    location = "separateLine"

    [language-server.vscode-eslint-language-server.config.codeAction.showDocumentation]
    enable = true

    [language-server.vscode-eslint-language-server.config.workingDirectory]
    mode = "location" # "auto"

[[language]]
name             = "typescript"
language-servers = ["vscode-eslint-language-server", "tailwindcss-ls", "typescript-language-server"]
auto-format      = true

  [language.formatter]
  command = "bash"
  args    = ["-c", "prettier-eslint '%{buffer_name}'  '%{current_working_directory}'"]

[[language]]
name             = "tsx"
language-servers = ["vscode-eslint-language-server", "tailwindcss-ls", "typescript-language-server"]
auto-format      = true

  [language.formatter]
  command = "bash"
  args    = ["-c", "prettier-eslint '%{buffer_name}'  '%{current_working_directory}'"]

[[language]]
name             = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name        = "xml"
auto-format = true

  [language.formatter]
  command = "prettier"
  args    = ["--parser=html", "--stdin-filepath", "%{buffer_name}"]

[[language]]
name             = "css"
file-types       = ["css", "scss", "tcss"]
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]
